site_name: Christmas Light Show
site_description: Documentation about the Christmas Light Show
site_url: https://thealmostengineer.com
copyright: Copyright 2020

# repository information
repo_url: https://github.com/almostengr/christmaslights
repo_name: Github
remote_name: origin
remote_branch: gh-pages

# Development server details
dev_addr: 192.168.57.117:8000
  
extra_css: [css/extra.css]


# Appearance
theme:
  name: readthedocs
  highlightjs: false

  # name: material
  # palette: 
  #   primary: teal
  #   accent: red
  #   # scheme: slate
  # features:
  #   - navigation.tabs
  # # hide: 
  # #   - navigation
  language: en

use_directory_urls: true
strict: false

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

extra:
  generator: false